/* Portfolio by Avdesh Jadon — Full Stack Developer & Software Tester. */
"use client";

import { createContext, useContext, type ReactNode } from "react";

export type Lang = "en";

export const DICT: Record<string, string> = {

  "nav.home": "Home",
  "nav.about": "About",
  "nav.work": "Work",
  "nav.contact": "Contact",
  "nav.menu": "Open menu",
  "nav.close": "Close menu",

  "intro.scroll": "Scroll to enter",

  "hero.kicker": "Full Stack Developer & Software Tester",
  "hero.h1a": "Software that feels",
  "hero.h1aEm": "obvious.",
  "hero.h1b": "Code that simply",
  "hero.h1bEm": "works.",
  "hero.sub":
    "I build and test digital products end to end — frontend, backend, APIs, QA — with one obsession: making the complex feel effortless.",
  "hero.cta1": "View My Work",
  "hero.cta2": "See How I Work",
  "hero.scroll": "Scroll to Explore",
  "stat.projects": "Projects Completed",
  "stat.years": "Years of Experience",
  "stat.countries": "Countries Worked With",
  "stat.satisfaction": "Client Satisfaction",

  "about.eyebrow": "About",
  "about.h2a": "Code is how I think —",
  "about.h2b": "shipping is how I",
  "about.h2Em": "aim",
  "about.h2c": "it.",
  "about.m1": "Sophia Antipolis Innovation Hackathon — LockAI",
  "about.m2": "Years of cross-functional dev & product experience",
  "about.m3": "Revenue generated by conversion-focused work",
  "about.m4": "Tonnes of CO₂ the products I build aim to avoid by 2050",
  "about.edu":
    "MSc International Business · Montpellier Business School · 2024–2026 · Global Market Intelligence · Strategic Leadership · AI in Business",
  "about.cta": "Explore My Work",

  "journey.eyebrow": "My Journey",
  "journey.enter": "Scroll to travel",
  "journey.chapter": "Chapter",
  "journey.lede":
    "From Telangana to the Côte d’Azur — the chapters that turned a salesperson into a full stack developer.",

  "stack.eyebrow": "Toolkit",
  "stack.h2": "My Tech",
  "stack.h2Em": "Stack.",
  "stack.lede":
    "The tools I use to build, test and ship — from the first component to production, with QA on every step.",
  "stack.count": "tools",
  "stack.disciplines": "disciplines",

  "hunch.eyebrow": "My Creative Hunch",

  "work.eyebrow": "Featured Work",
  "work.h2a": "Selected projects,",
  "work.h2b": "built to",
  "work.h2Em": "ship.",
  "work.lede":
    "Frontend, backend, full-stack apps and QA — each project a different capability, all one practice.",
  "work.open": "Open case study",
  "work.hint": "SCROLL TO BROWSE",

  "exp.eyebrow": "Experience",
  "exp.h2": "Where I built my",
  "exp.h2Em": "judgment.",
  "exp.worked": "What I worked on",
  "exp.impact": "Impact",
  "exp.tools": "Tools & skills",
  "exp.hint": "SCROLL · CLICK TO JUMP",
  "type.Internship": "Internship",
  "type.Full-time": "Full-time",
  "type.Hackathon": "Hackathon",
  "type.Freelance": "Freelance",

  "cert.introLabel": "Introduction",
  "cert.introTitle1": "VERIFIED",
  "cert.introTitle2": "CREDENTIALS",
  "cert.introBody":
    "Continuous, applied learning across development, data, testing and AI — the technical base underneath the product work.",
  "cert.introNote":
    "Five programmes · Coursera, LinkedIn Learning and hands-on portfolio projects.",
  "cert.eyebrow": "Credentials",
  "cert.h2": "Credentials",
  "cert.lede":
    "Professional certifications and credentials earned throughout my development and technology journey.",
  "cert.certified": "Certified",
  "cert.brandRole": "Full Stack Developer & Software Tester",
  "cert.issuerTBC": "Issuer — to confirm",
  "cert.certification": "Certification",
  "cert.verified": "✓ Verified",
  "cert.onRequest": "Credential on request",
  "cert.issuedBy": "Issued by",
  "cert.year": "Year",
  "cert.id": "Credential ID",
  "cert.tbc": "To confirm",
  "cert.skills": "Skills",
  "cert.verify": "Verify credential ↗",
  "cert.foot": "Credentials",

  "gallery.eyebrow": "The Archive",
  "gallery.h2a": "The people behind",
  "gallery.h2Em": "the work",
  "gallery.lede":
    "The people, moments and experiences that shaped the work behind the screen.",
  "gallery.alt": "A moment with the people behind the work",
  "gallery.frames": "Frames",
  "gallery.hint": "Scroll to travel the archive",

  "connect.eyebrow": "Let’s Connect",
  "connect.h2a": "Let’s build what’s",
  "connect.h2Em": "next.",
  "connect.lede":
    "I’m open to full stack development, QA engineering and software testing roles, collaborations and good conversations — if you’re building something people should love, I’d like to hear about it.",
  "connect.cta": "Start a Conversation",
  "connect.credit": "Developed by",
  "connect.top": "Back to top ↑",

  "case.back": "← Back to work",
  "case.kicker": "Case Study",
  "case.role": "Role",
  "case.timeline": "Timeline",
  "case.focus": "Focus",
  "case.site": "Live product",
  "case.repo": "Source",
  "case.cover": "COVER",
  "case.context": "Context",
  "case.problem": "The Problem",
  "case.process": "Process",
  "case.decisions": "Key Decisions",
  "case.outcome": "Outcome",
  "case.reflection": "Reflection",
  "case.all": "← All projects",
  "case.next": "Next project",

  "lab.back": "← PORTFOLIO",
  "lab.hint": "LAB · TUNNEL TYPE — SCROLL TO TRAVEL · MOVE THE MOUSE",

  "nf.label": "404 — NOT FOUND",
  "nf.h1": "This page went",
  "nf.h1Em": "off the grid.",
  "nf.cta": "Back to the portfolio →",
};

type Ctx = { lang: Lang; t: (k: string) => string };

const LanguageContext = createContext<Ctx>({
  lang: "en",
  t: (k) => DICT[k] ?? k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  return (
    <LanguageContext.Provider value={{ lang: "en", t: (k) => DICT[k] ?? k }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);

export function L<T>(
  _lang: Lang,
  item: T,
  field: keyof T & string
): string {
  return item[field] as unknown as string;
}